---
# tasks file for apigee-lvm-increase-volume-size

- name: Install gdisk
  yum:
    name: gdisk
    state: present

- name: Create partition from available space
  shell: "/usr/sbin/sgdisk --new {{ partnum }}:$(/usr/sbin/sgdisk -F):$(/usr/sbin/sgdisk -E) --mbrtogpt --typecode {{ partnum }}:{{ typecode }} --print {{ device_path }}"

- name: Re-read partition table
  shell: /usr/sbin/partprobe

- name: Create physical volume from partion
  shell: "/usr/sbin/pvcreate {{ device_path }}{{ partnum}}"

#- name: Create physical volume and extend volume group from partition
#  lvg:
#    pvs: "{{ device_path }}{{ partnum }}"
#    vg: "{{ volume_name }}"

- name: Extend local volume from added physical volume
  lvol:
    vg: "{{ volume_name }}"
    lv: "{{ logical_volume_name }}"
    pvs: "{{ device_path }}{{ partnum }}"
    shrink: no
    state: present
    size: "+{{ percent_volume_extend }}%FREE"

- name: Resize2fs to reflect the space with file system
  shell: "/usr/bin/resize2fs /dev/mapper/{{ volume_name }}-{{ logical_volume_name }}"
